services:
  postgres:
    image: postgres:15
    container_name: postgres_container
    restart: always
    ports:
      - "5432:5432" # Expose PostgreSQL on port 5432
    environment:
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
    env_file:
      - ".env"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: